// <auto-generated />
using System;
using EComm_2011501158.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EComm_2011501158.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230711181903_Migrasi_ulang")]
    partial class Migrasi_ulang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EComm_2011501158.Shared.ItemKereta", b =>
                {
                    b.Property<int>("IdPesanan")
                        .HasColumnType("int");

                    b.Property<int>("IdProduk")
                        .HasColumnType("int");

                    b.Property<int>("IdVarian")
                        .HasColumnType("int");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaVarian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("IdPesanan", "IdProduk", "IdVarian");

                    b.HasIndex("IdProduk");

                    b.HasIndex("IdVarian");

                    b.ToTable("PesananProduk");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Kategori", b =>
                {
                    b.Property<int>("IdKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategori"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategori");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            IdKategori = 1,
                            Nama = "Gitar"
                        },
                        new
                        {
                            IdKategori = 2,
                            Nama = "Bass"
                        },
                        new
                        {
                            IdKategori = 3,
                            Nama = "Keyboard/Synth"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.KonfirmasiPesanan", b =>
                {
                    b.Property<int>("IdPesanan")
                        .HasColumnType("int");

                    b.Property<int>("IdKonfirmasi")
                        .HasColumnType("int");

                    b.Property<string>("BankTransfer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumlahTransfer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TglKonfirmasi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglTransfer")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPesanan", "IdKonfirmasi");

                    b.ToTable("KonfirmasiPesanan");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Pengguna", b =>
                {
                    b.Property<int>("IdPengguna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPengguna"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("AlamatPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TeleponPengguna")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("TglLahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPengguna");

                    b.ToTable("Pengguna");

                    b.HasData(
                        new
                        {
                            IdPengguna = 1,
                            Admin = true,
                            AlamatPengguna = "Jl. Budiyanto No.2 Jakarta",
                            EmailPengguna = "Khaliskafka@mail.com",
                            FotoPengguna = "https://i.pinimg.com/564x/b6/24/7a/b6247a4b03bc5a296ac7f694b6b72863.jpg",
                            KonfirmPassword = "admin123",
                            NamaPengguna = "kafka khalis",
                            Password = "admin123",
                            Status = true,
                            TeleponPengguna = "08193818311",
                            TglLahir = new DateTime(2015, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "kafka17"
                        },
                        new
                        {
                            IdPengguna = 2,
                            Admin = false,
                            AlamatPengguna = "Jl. Budiyanto No.2 Jakarta",
                            EmailPengguna = "Khaliskafka@mail.com",
                            FotoPengguna = "https://i.pinimg.com/564x/c2/3a/2b/c23a2bf30698cda8384dedf791ea274b.jpg",
                            KonfirmPassword = "pengguna123",
                            NamaPengguna = "kafka khalis",
                            Password = "pengguna123",
                            Status = true,
                            TeleponPengguna = "08193818311",
                            TglLahir = new DateTime(2015, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "pkafka"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Pesanan", b =>
                {
                    b.Property<int>("IdPesanan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPesanan"));

                    b.Property<DateTime>("TglPesanan")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPesanan");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Produk", b =>
                {
                    b.Property<int>("IdProduk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduk"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GambarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HargaOrginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdKategori")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduk");

                    b.HasIndex("IdKategori");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            IdProduk = 1,
                            DateCreated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5070),
                            DateUpdated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5071),
                            Deskripsi = "Bawalah pengalaman bermain gitar metal Anda ke level berikutnya dengan Gitar Ibanez GRGR121DX. Didesain khusus untuk menghadirkan suara yang menghancurkan dan tampilan yang mengesankan, gitar ini menjadi pilihan terbaik bagi para pemain metal dan content creator.  novel yang bercerita tentang pembunuhan seorang pegawai Departemen Luar Dibungkus dalam warna hitam yang elegan, Gitar Ibanez GRGR121DX menawarkan estetika yang kuat dan tampilan yang tangguh. Dengan desain yang ergonomis, ini adalah gitar yang nyaman dipegang dan dapat dipakai selama berjam-jam bermain, sehingga memungkinkan Anda untuk fokus pada kreasi musik terbaik Anda.",
                            GambarUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS8NOnBysRWmlIR7-yEwxETas9pzA5IbUAFOJ4ia0npOrXkKIb9IcVydA4abKB7FYcJb8Ujy04o15SCIznDRzK2T3Ja5hnMNQe0AszhmxaEh5XtupTr08_47Q&usqp=CAE",
                            Harga = 3000.000m,
                            HargaOrginal = 4500.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Ibanez Electric Guitar GRGR121DX-BKF"
                        },
                        new
                        {
                            IdProduk = 2,
                            DateCreated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5075),
                            DateUpdated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5075),
                            Deskripsi = "THadapi intensitas musik metal dengan kekuatan Gitar iGrg140wh C14. Dirancang dengan kombinasi sempurna antara keindahan dan kekuatan, gitar ini memberikan pengalaman bermain yang epik dan cocok untuk penggemar lagu-lagu metal. Gitar iGrg140wh C14 membanggakan kualitas kayu maple yang luar biasa. Kayu maple memberikan resonansi yang kaya dan tajam, menghasilkan suara yang cocok untuk lagu-lagu metal dengan karakteristik yang diperlukan untuk menciptakan riff berat dan solo yang menghancurkan. Apakah Anda sedang mencari suara yang melengking atau distorsi yang intens, gitar ini akan memberikan kejelasan dan kekuatan yang Anda butuhkan.\r\n\r\nDilengkapi dengan bridge original Ibanez, gitar ini menjamin pemindahan getaran Jadikan Gitar iGrg140wh C14 sebagai senjata pilihan Anda dalam menjelajahi genre metal. Dari suara yang kuat hingga kualitas kayu maple yang indah, gitar ini menggabungkan segala yang Anda butuhkan untuk menghasilkan musik metal yang menakjubkan. Siapkan diri Anda untuk menghancurkan panggung dengan performa yang tak terlupakan menggunakan gitar ini. ",
                            GambarUrl = "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTxEW4dCpLuVrxm3TAjqfJ2DYoluvYJW8dJ6irolidEXAGcpgDlHXXIW50RWa5eeWHFeBZUNQBfgHrslBL4k2prIvaZdQIgdrcqwGgBccyl5HawmR-CondL&usqp=CAE",
                            Harga = 6000.000m,
                            HargaOrginal = 800.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = " Ibanez Electric Guitar Grg140wh C14"
                        },
                        new
                        {
                            IdProduk = 3,
                            DateCreated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5078),
                            DateUpdated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5079),
                            Deskripsi = "Dummy untuk Deskripsi Produk: Gitar Ibanez JEMJRL-WH Steve Vai Signature\r\n\r\nRasakan keajaiban gitar Steve Vai dengan Gitar Ibanez JEMJRL-WH Steve Vai Signature. Didesain khusus untuk menggambarkan gaya bermain dan inovasi musikal Steve Vai, gitar ini merupakan pilihan sempurna bagi para penggemar dan pemain gitar yang ingin menghadirkan suara dan estetika khasnya. Dengan warna putih yang memukau, Gitar Ibanez JEMJRL-WH memancarkan keanggunan dan keunikan. Dalam kombinasi dengan desain signature Steve Vai yang legendaris, gitar ini menunjukkan karakter yang tidak ada duanya di panggungGitar ini dilengkapi dengan fitur-fitur khusus yang membuatnya menjadi ciri khas Steve Vai. Dari neck berbentuk khas \"Wizard III\" yang memungkinkan permainan yang cepat dan presisi hingga tremolo bridge yang ikonik, gitar ini memungkinkan pemain untuk mengekspresikan diri mereka secara bebas dan kreatif. ",
                            GambarUrl = "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRMaB6M03vahg40u23jpU8rKfhF2wJBvArUEOtVQpPq-NKZ1l0wyWKqs7XUqlNkkSvtJJYJEQZKtKSLt-kkmepQPX4g-cvJBFPO-NCJqJVDyGHIHJwKJnlIrw&usqp=CAE",
                            Harga = 9000.000m,
                            HargaOrginal = 8600.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Ibanez JEMJRL-WH Steve Vai Signature"
                        },
                        new
                        {
                            IdProduk = 4,
                            DateCreated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5082),
                            DateUpdated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5083),
                            Deskripsi = "Hadiri panggung dengan kekuatan dan keandalan Gitar Yamaha TRBX174 Electric Bass. Dirancang untuk memenuhi kebutuhan para pemain bass yang mencari instrumen yang tangguh dan dapat diandalkan, gitar ini menawarkan suara yang luar biasa dan kenyamanan bermain yang tak tertandingi.",
                            GambarUrl = "https://id.yamaha.com/id/files/Image-Index_BBNE2_1080x1080_ac739522bc0daea2ea8fc4a55cd6c2cc.jpg?impolicy=resize&imwid=396&imhei=396",
                            Harga = 6000.000m,
                            HargaOrginal = 8600.000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Yamaha TRBX174 Electric Bass "
                        },
                        new
                        {
                            IdProduk = 5,
                            DateCreated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5086),
                            DateUpdated = new DateTime(2023, 7, 12, 1, 19, 3, 148, DateTimeKind.Local).AddTicks(5086),
                            Deskripsi = "Jelajahi dunia suara yang tak terbatas dengan Synth Korg, alat yang dirancang untuk memenuhi kebutuhan musisi kreatif dan produser modern. Menggabungkan kecanggihan teknologi dengan kualitas suara yang luar biasa, Synth Korg adalah kunci menuju eksplorasi musik yang tak terbatas.",
                            GambarUrl = "https://pusatsoundsystem.com/wp-content/uploads/Korg-Minilogue-XD-350x350.jpg",
                            Harga = 12000.000m,
                            HargaOrginal = 16000.000m,
                            IdKategori = 3,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Yamaha TRBX174 Electric Bass "
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.ProdukVarian", b =>
                {
                    b.Property<int>("IdProduk")
                        .HasColumnType("int");

                    b.Property<int>("IdVarian")
                        .HasColumnType("int");

                    b.Property<decimal>("HargaOriVarian")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HargaVarian")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProduk", "IdVarian");

                    b.HasIndex("IdVarian");

                    b.ToTable("ProdukVarian");

                    b.HasData(
                        new
                        {
                            IdProduk = 1,
                            IdVarian = 1,
                            HargaOriVarian = 1000.000m,
                            HargaVarian = 1200.000m
                        },
                        new
                        {
                            IdProduk = 1,
                            IdVarian = 2,
                            HargaOriVarian = 3000.000m,
                            HargaVarian = 2100.000m
                        },
                        new
                        {
                            IdProduk = 2,
                            IdVarian = 1,
                            HargaOriVarian = 1000.000m,
                            HargaVarian = 900.000m
                        },
                        new
                        {
                            IdProduk = 2,
                            IdVarian = 2,
                            HargaOriVarian = 4200.000m,
                            HargaVarian = 3200.000m
                        },
                        new
                        {
                            IdProduk = 3,
                            IdVarian = 4,
                            HargaOriVarian = 12400.000m,
                            HargaVarian = 13050.000m
                        },
                        new
                        {
                            IdProduk = 3,
                            IdVarian = 1,
                            HargaOriVarian = 1200.000m,
                            HargaVarian = 2400.000m
                        },
                        new
                        {
                            IdProduk = 4,
                            IdVarian = 1,
                            HargaOriVarian = 1000.000m,
                            HargaVarian = 2050.000m
                        },
                        new
                        {
                            IdProduk = 4,
                            IdVarian = 2,
                            HargaOriVarian = 3060.000m,
                            HargaVarian = 3200.000m
                        },
                        new
                        {
                            IdProduk = 4,
                            IdVarian = 4,
                            HargaOriVarian = 8360.000m,
                            HargaVarian = 7200.000m
                        },
                        new
                        {
                            IdProduk = 5,
                            IdVarian = 2,
                            HargaOriVarian = 8600.000m,
                            HargaVarian = 6520.000m
                        },
                        new
                        {
                            IdProduk = 5,
                            IdVarian = 3,
                            HargaOriVarian = 12600.000m,
                            HargaVarian = 10520.000m
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Varian", b =>
                {
                    b.Property<int>("IdVarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVarian"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVarian");

                    b.ToTable("Varian");

                    b.HasData(
                        new
                        {
                            IdVarian = 1,
                            Nama = "Custom /KW"
                        },
                        new
                        {
                            IdVarian = 2,
                            Nama = "Original"
                        },
                        new
                        {
                            IdVarian = 3,
                            Nama = "Special Edition Presitage"
                        },
                        new
                        {
                            IdVarian = 4,
                            Nama = "Special Edition Singnature"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.ItemKereta", b =>
                {
                    b.HasOne("EComm_2011501158.Shared.Pesanan", "Pesanan")
                        .WithMany("PesaananProduk")
                        .HasForeignKey("IdPesanan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EComm_2011501158.Shared.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("IdProduk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EComm_2011501158.Shared.Varian", "Varian")
                        .WithMany()
                        .HasForeignKey("IdVarian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");

                    b.Navigation("Produk");

                    b.Navigation("Varian");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.KonfirmasiPesanan", b =>
                {
                    b.HasOne("EComm_2011501158.Shared.Pesanan", "Pesanan")
                        .WithMany()
                        .HasForeignKey("IdPesanan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pesanan");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Produk", b =>
                {
                    b.HasOne("EComm_2011501158.Shared.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("IdKategori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.ProdukVarian", b =>
                {
                    b.HasOne("EComm_2011501158.Shared.Produk", "Produk")
                        .WithMany("ProdukVarians")
                        .HasForeignKey("IdProduk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EComm_2011501158.Shared.Varian", "Varian")
                        .WithMany()
                        .HasForeignKey("IdVarian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");

                    b.Navigation("Varian");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Pesanan", b =>
                {
                    b.Navigation("PesaananProduk");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Produk", b =>
                {
                    b.Navigation("ProdukVarians");
                });
#pragma warning restore 612, 618
        }
    }
}
