// <auto-generated />
using System;
using EComm_2011501158.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EComm_2011501158.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230515153140_PenggunaMigrations")]
    partial class PenggunaMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EComm_2011501158.Shared.Kategori", b =>
                {
                    b.Property<int>("IdKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategori"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategori");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            IdKategori = 1,
                            Nama = "Horror"
                        },
                        new
                        {
                            IdKategori = 2,
                            Nama = "Drama"
                        },
                        new
                        {
                            IdKategori = 3,
                            Nama = "fantasi"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Pengguna", b =>
                {
                    b.Property<int>("IdPengguna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPengguna"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("AlamatPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeleponPengguna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglLahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPengguna");

                    b.ToTable("Pengguna");

                    b.HasData(
                        new
                        {
                            IdPengguna = 1,
                            Admin = true,
                            AlamatPengguna = "Jl. Budiyanto No.2 Jakarta",
                            EmailPengguna = "Khaliskafka@mail.com",
                            FotoPengguna = "https://i.pinimg.com/564x/b6/24/7a/b6247a4b03bc5a296ac7f694b6b72863.jpg",
                            KonfirmPassword = "",
                            NamaPengguna = "kafka khalis",
                            Password = "admin123",
                            TeleponPengguna = "08193818311",
                            TglLahir = new DateTime(2015, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "kafka17"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Produk", b =>
                {
                    b.Property<int>("IdProduk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduk"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GambarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HargaOrginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdKategori")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduk");

                    b.HasIndex("IdKategori");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            IdProduk = 1,
                            DateCreated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4672),
                            DateUpdated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4673),
                            Deskripsi = "Misteri Tujuh Lonceng adalah sebuah novel yang bercerita tentang pembunuhan seorang pegawai Departemen Luar Negeri Inggris di sebuah pemondokan, yaitu Pemondokan Chimney. Setelah itu terjadi juga pembunuhan terhadap seorang pria yang tidak lain adalah teman orang yang terbunuh di pemondokan Chimney.",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/id/4/4c/The_Seven_Dials_Mystery_First_Edition_Cover_1929.jpg",
                            Harga = 99.999m,
                            HargaOrginal = 100.000m,
                            IdKategori = 1,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Misteri Tujuh Lonceng"
                        },
                        new
                        {
                            IdProduk = 2,
                            DateCreated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4677),
                            DateUpdated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4677),
                            Deskripsi = "The Witcher adalah rangkaian enam novel fantasi dan 15 cerita pendek  yang ditulis oleh penulis Polandia Andrzej SapkowskiSerial ini berputar di sekitar \"penyihir\" eponymous, Geralt of Rivia ",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/en/8/84/Season_of_Storms_Orion.jpg",
                            Harga = 70.000m,
                            HargaOrginal = 12.0000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Season of Storms"
                        },
                        new
                        {
                            IdProduk = 3,
                            DateCreated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4680),
                            DateUpdated = new DateTime(2023, 5, 15, 22, 31, 39, 774, DateTimeKind.Local).AddTicks(4681),
                            Deskripsi = "The Lord of the Rings adalah sebuah novel epik   fantasi tinggi [a] oleh penulis dan sarjana Inggris J. R. R. Tolkien. Bertempat di Middle-earth, ceritanya dimulai sebagai sekuel dari buku anak-anak Tolkien tahun 1937 The Hobbit, tetapi akhirnya berkembang menjadi karya yang jauh lebih besar. ",
                            GambarUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/First_Single_Volume_Edition_of_The_Lord_of_the_Rings.gif/220px-First_Single_Volume_Edition_of_The_Lord_of_the_Rings.gif",
                            Harga = 70.000m,
                            HargaOrginal = 120.000m,
                            IdKategori = 2,
                            IsDeleted = false,
                            IsPublic = true,
                            Nama = "Lord of the rings"
                        });
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Varian", b =>
                {
                    b.Property<int>("IdVarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVarian"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVarian");

                    b.ToTable("Varian");
                });

            modelBuilder.Entity("EComm_2011501158.Shared.Produk", b =>
                {
                    b.HasOne("EComm_2011501158.Shared.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("IdKategori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });
#pragma warning restore 612, 618
        }
    }
}
